### ISSUE TITLE
Use bsddb3 for Python 2.7

### ISSUE THREAD

**Issue by MasterOdin** [c-w/gutenberg#104]
While Python 2.7 does come with a builtin [bsddb](https://docs.python.org/2/library/bsddb.html) module, it was depreciated in 2.6. It seems to me that we should just migrate wholly to using [bsddb3](https://www.jcea.es/programacion/pybsddb.htm) for all supported versions and which would also simplify the setup_requires for the project and also allow us to add a Pipfile.

Thoughts @c-w, @hugovk?

**Comment by c-w** [comment]
I'd agree that simplification is a good thing. However, installing BSD-DB is a source of errors for some users (e.g. see #101) so it's nice to have the very simple Python 2.7 setup which just works out of the box.

Maybe a good compromise could be to drop support for the built-in BSD-DB module and at the same time also add a Dockerfile that does all the required setup? In this way we keep a very easy to use version (Docker) while also simplifying the code (single BSD-DB library). Thoughts?

**Comment by hugovk** [comment]
I've also had problems setting up with BSD-DB on another machine (not this one). This newer machine one was fine to set up.

A Dockerfile might make it easier for some, but isn't necessarily easy for beginners.

* It's not that long until Python 2.7 is EOL: https://pythonclock.org. 

* Some projects have committed to dropping 2.7 on or before 2020-01-01: http://python3statement.org.

How about deciding when to ditch 2.7, and keeping 2.7 as it is until then (but don't let that prevent adding a Dockerfile)?

**Comment by hugovk** [comment]
By the way, here's the pip installs for gutenberg from PyPI for April 2018:


| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.6            |  40.91% |             36 |
| 2.7            |  34.09% |             30 |
| 3.5            |  23.86% |             21 |
| 3.4            |   1.14% |              1 |
| Total          |         |             88 |

Source: `pypinfo --start-date 2018-04-01 --end-date 2018-04-30 --percent --markdown gutenberg pyversion`

Good to see two thirds are already Python 3.

**Comment by hugovk** [comment]
Is it time to drop Python 2?

* https://python2woop.pw
* https://pythonclock.org
* https://python3statement.org

**Comment by c-w** [comment]
Given that there isn't a ton of work happening on this repo, I would suggest to keep the current setup. As such, closing this issue. Feel free to reopen if you feel strongly otherwise.
