### ISSUE TITLE
API v2

### ISSUE THREAD

**Issue by c-w** [c-w/Gutenberg#11]
Now that we have a couple of use-cases for the Gutenberg library, I figure it would be a good time to refactor the API. The current implementation was okay to get off the ground, however, the current API also turns out to be hard to test and over-complicated.

@MasterOdin, @sethwoodworth:
- What do you think about this?
- What are your use-cases for this library i.e. what functionality do you really need?

Currently I'm thinking of a really simple API:
```haskell
type Text = String
type Attribute = (String, String)
type Uid = Integer

_text_for_uid :: Uid -> Text -- returns the text for a given UID
_attributes_for_uid :: Uid -> [Attribute] -- returns the properties of a given UID e.g. author, 

texts_for_attribute :: Attribute -> [Text] -- returns all the texts for a given attribute-value combination such as ('author', 'Jules Verne'), ('year', '1996') or ('title', 'Moby Dick')
```

`_attributes_for_uid` parses the Gutenberg meta-data tarball using RDF to extract all attributes for all the texts. `_text_for_uid` takes care of downloading the texts (and/or storing them on disk). The last function is trivially defined in terms of the first two.

**Comment by c-w** [comment]
Thanks for your inputs. I've finally found some time to work on this again.

There are really three things that this package is doing, which was causing my issues with the initial version of the API:

1. Get texts from Project Gutenberg.
2. Search the meta-data of the texts.
3. Clean up the texts.

I'll re-structure the API along those lines.

For now, I've split out the bit of code that post-processes the Project Gutenberg texts to remove the legal disclaimers and other headers/footers (use-case 3. above). This is the most mature part of the project and quite usable on its own.

The split-out package is [gutenberg_cleaner](https://github.com/c-w/GutenbergCleaner). @sethwoodworth - you might want to have a look at this new package and let me know of any texts where the headers/footers are not correctly parsed out correctly.

**Comment by sethwoodworth** [comment]
I'll take a look!  Thank you

**Comment by c-w** [comment]
I'm almost code complete on a clean-room re-implementation of the library with a much clearer and more testable API.  Below is a preview of the new API - feel free to leave a comment if you feel strongly about any of the things you see.

Using the new API is a lot simpler than previously.

```python
def load_etext(etextno):
    """Returns a unicode representation of the Project Gutenberg text with the given identifier.

    """
    pass


def get_metadata(feature_name, etextno):
    """Looks up a meta-data value for a particular e-text.

    >>> get_metadata('title', 2701)
    u'Moby Dick; or The Whale'

    >>> get_metadata('author', 2701)
    u'Melville, Herman'

    """
    pass


def get_etexts(feature_name, value):
    """Looks up all the texts that have a particular meta-data value.

    >>> get_etexts('title', 'Moby Dick; or The Whale')
    [2701]

    >>> get_etexts('author', 'Melville, Herman')
    [15, 1900, 2489, 2694, 2701, 4045, 8118, 9146, 9147, 9268, 9269, 10712, 11231, 12384, 12841, 13720, 13721, 15422, 15859, 21816, 23969, 28656, 28794, 34970]

    """
    pass
```

The `get_{etexts,metadata}` functions reflectively delegate work to MetadataExtractor objects. This means that extending the API with new meta-data features is as simple as creating a new sub-class of  MetadataExtractor and loading it into the Python run-time.

```python
class MetadataExtractor(object):
    _metadata = load_metadata()  # this is the full Project Gutenberg meta-data RDF graph

    @abstractlassmethod
    def feature_name(cls): pass

    @abstractlassmethod
    def get_metadata(cls, etextno): pass

    @abstractlassmethod
    def get_etexts(cls, feature_value): pass
```

**Comment by MasterOdin** [comment]
I would argue that it would be important for get_etexts to not only support one feature/value pair but potentially multiple. 

A potential use case that illustrates this would be how would I get only the german books by the author "Various".

The solution as proposed by your API would be:
```
texts = get_etexts('author','various')
final_list = []
for text in texts:
    if get_metadata('language', text) != 'german':
        pass
    final_list.append(text)
```

which is somewhat weird as the API would ideally handle that with something like:
```
texts = get_etexts({'author':'various','language':'german'})
```

I'm also curious to how exactly load_metadata would work as get_metadata still making some sort of SPARQL call or is it rather loading the SPARQL data into some sort of dictionary/list structure that's a bit easier to parse straight in python.

**Comment by sethwoodworth** [comment]
Django makes chaining query filters really easy.  abstractclassmethods return self, which allows for chaining of `.filter()` commands.

    texts = MetadataExtractor.get_etexts('author', 'various').get_etexts('language', 'german')

**Comment by c-w** [comment]
### Query composition

How about having the `get_etexts` return a set of texts instead of a list? This would be more semantically correct (we're returning a set of results that inherently is without order) and would allow simple query composition without needing to add any special mechanisms.

```python
texts = get_etexts('author', 'various') & get_etexts('language', 'german')
```


### Metadata

The `load_metadata` function returns an [rdflib.Graph](https://github.com/RDFLib/rdflib/blob/master/rdflib/graph.py) of all the information in the Project Gutenberg meta-data catalog. The graph supports both SPARQL queries and indexing based on triple-matching.
Currently loading the meta-data graph is quite slow (MVP implementation de-serializes the graph from disk into memory which has to load ~100MB of compressed RDF data, ~800MB uncompressed). Going forward, there are a number of ways to improve performance (e.g. use a graph backed by an on-disk database instead of having to load the entire graph into memory).

Here is an example of how we'd write a MetadataExtractor that gets title information.

```python
from rdflib.namespace import DCTERMS
from rdflib.term import URIRef


def etext_to_uri(etext):
    uri = r'http://www.gutenberg.org/ebooks/{}'.format(etext)
    return URIRef(uri)


def uri_to_etext(uri):
    return int(os.path.basename(uri.toPython()))


class TitleExtractor(MetadataExtractor):
    @classmethod
    def feature_name(cls):
        return 'title'

    @classmethod
    def get_metadata(cls, etextno):
        query = cls._metadata[etext_to_uri(etextno) : DCTERMS.title : ]  # finds all the triples where the subject==etext and the predicate==title
        try:
            return next(query).toPython()
        except StopIteration:
            return None

    @classmethod
    def get_etexts(cls, feature_value):
        query = cls._metadata[ : DCTERMS.title : ]  # find all the triples where the predicate==title
        return [uri_to_etext(uri) for uri, value in query
                if value.toPython() == feature_value]
```

**Comment by MasterOdin** [comment]
I guess my primary concern would be speed of doing multiple queries/finding triples against the entire Gutenberg graph (as you mentioned it was hundreds of MB of data into memory) and then doing set/list manipulations as opposed to setting up one query within SPARQL (assuming it's possible, as I'm not 100% sure as I haven't played with it enough) which would return the wanted result.
