### ISSUE TITLE
Avoid downloading the cache?

### ISSUE THREAD

**Issue by fickas** [c-w/gutenberg#115]
I'd like to download 2701 text **and** the meta-data that goes with it. Can I get the 2701 meta-data without downloading the entire cache?

Thanks.

**Comment by hugovk** [comment]
Here's a repo containing metadata generated using this library. Does this help?

https://github.com/hugovk/gutenberg-metadata

**Comment by c-w** [comment]
There's also https://github.com/c-w/gutenberg-http which you can set up as a web-service to fetch texts and metadata on-demand. Still requires the cache to be created on the server though.

**Comment by c-w** [comment]
@fickas I've re-instated a hosted version of [gutenberg-http](https://github.com/c-w/gutenberg-http) which makes it easier to pull down the metadata without having to install the gutenberg library. For example, to fetch the metadata for etext 2701, you can execute this:

```sh
curl https://gutenberg.justamouse.com/texts/2701
```

There's also a [demo-page](https://gutenberg.justamouse.com) available to explore the API.

Note though that for now the service is hosted on a single VM so I'm not making any promises about performance or uptime. If you wish to use this in production, I'd strongly spinning up your own deployment of [gutenberg-http](https://github.com/c-w/gutenberg-http).
