### ISSUE TITLE
Can this generate a CSV file of key Gutenberg metadata?

### ISSUE THREAD

**Issue by breck7** [c-w/gutenberg#127]
Aloha,
Can this generate a CSV file of the key metadata (title, author, year, text link) for Gutenberg books? If so, I can make a pretty cool tile in Ohayo to allow people to instantly do text analysis and other things on any gutenberg title (https://github.com/treenotation/ohayo/issues/24)

**Comment by hugovk** [comment]
Here's some JSON, last updated 7 months ago. 

https://github.com/hugovk/gutenberg-metadata

Not from this library, from https://github.com/c-w/Gutenberg.

**Comment by c-w** [comment]
Thanks for the pointer @hugovk. Closing this issue as the linked repository should contain a good starting point for any scripting needs.
