### ISSUE TITLE
Can't download the newest uploads

### ISSUE THREAD

**Issue by hugovk** [c-w/Gutenberg#23]
The two most recent uploads to Project Gutenberg are:

https://www.gutenberg.org/ebooks/50334
https://www.gutenberg.org/ebooks/50333

This code:

``` python
from gutenberg.acquire import load_etext
from gutenberg.cleanup import strip_headers

text = strip_headers(load_etext(50333)).strip()
print(text[:10])
text = strip_headers(load_etext(50334)).strip()
print(text[:10])
```

Produces:

```
Traceback (most recent call last):
  File "C:\temp\test.py", line 6, in <module>
    text = strip_headers(load_etext(50333)).strip()
  File "C:\Python27\lib\site-packages\gutenberg\acquire\text.py", line 71, in load_etext
    download_uri = _format_download_uri(etextno)
  File "C:\Python27\lib\site-packages\gutenberg\acquire\text.py", line 55, in _format_download_uri
    raise ValueError('download URI for {} not supported'.format(etextno))
ValueError: download URI for 50333 not supported
```

That's because it tries to download these but they don't exist:

http://www.gutenberg.lib.md.us/5/0/3/3/50333/50333.txt
http://www.gutenberg.lib.md.us/5/0/3/3/50333/50333-8.txt

Their Plain Text UTF-8 links look like this:

https://www.gutenberg.org/files/50334/50334-0.txt
https://www.gutenberg.org/cache/epub/50333/pg50333.txt

Is it because they're so new they've not been mirrored to http://www.gutenberg.lib.md.us, or something else?

**Comment by MasterOdin** [comment]
The method does require that the files be on ```http://www.gutenberg.lib.mid.us```, yes. The second link you posted though does exist and work so perhaps try again?

**Comment by hugovk** [comment]
OK, thanks for clearing it up!

Closing.

**Comment by anjabeth** [comment]
I'm also having trouble with this same error for The Iliad here: https://www.gutenberg.org/ebooks/6130, and this one doesn't seem to be super recent.  To check and make sure that it didn't happen for all books, I tried a couple of others. http://www.gutenberg.org/ebooks/16452, another version of The Iliad, has the same URI error, as does Welsh Fairy Tales (http://www.gutenberg.org/ebooks/9368). Books with bibrec numbers 7250, 5000, 3000, and 2000 all have the same error. 

But On The Origin of Species, http://www.gutenberg.org/ebooks/1228, works just fine, So maybe it is a recency issue, but if the #50333 exists there now, that seems unlikely. 

Any idea what the issue might be?

**Comment by c-w** [comment]
Resolving in favor of #81.
