### ISSUE TITLE
Query by language

### ISSUE THREAD

**Issue by MaxNoe** [c-w/Gutenberg#33]
Could you add a possibility to query by the language?

**Comment by c-w** [comment]
Hi @MaxNoe. Thanks for getting in touch.

I'm currently pretty busy with other commitments, so I can't make any promises about shipping new features for Gutenberg in a reasonable time-frame.

However, it's actually pretty straight-forward to add a new extractor ([example pull request](https://github.com/c-w/Gutenberg/pull/37/files)), so why don't you give it a shot and try to implement the functionality yourself? Feel free to give me a shout if you have any trouble.

**Comment by ikarth** [comment]
I've added pull request #50, which adds three new extractors, for languages, copyright status, and subject.
