### ISSUE TITLE
Cannot install on Windows to get to back up SQL option

### ISSUE THREAD

**Issue by lizrodrigues** [c-w/Gutenberg#42]
Hi,

I'm a newbie, but I've spent a few hours trying to work through documentation & forums, and so far I have not found a work around for the Berkeley db dependency. It will not let me install gutenberg at all, so I can't make use of the back up sql option you mentioned putting in. Have others noted this problem, and is there a way to install more directly than pip that would allow me to install it?

Thank you for your time,
Liz

**Comment by ikarth** [comment]
On Windows, the easiest way I've found to work around it is [this suggestion for installing the bsddb3 binary](http://stackoverflow.com/questions/33714698/installing-bsddb3-6-1-1-in-windows-filenotfounderror-db-include-db-h) from the [Unofficial Windows Binaries for Python Extension Packages](http://www.lfd.uci.edu/~gohlke/pythonlibs/).

**Comment by c-w** [comment]
Thanks for the tip, @ikarth. I've created #68 to add pythonlibs instructions to the readme.

Going forward, we can also make the setup.py smarter and automatically download the correct wheel if we're installing the package on Windows.
