### ISSUE TITLE
get_metadata('author') behavior (alias vs. name)

### ISSUE THREAD

**Issue by keithohara** [c-w/Gutenberg#43]
I have installed the library via pip with python2.7 on ubuntu 14.04. 

I was wondering if this kind of author behavior to be expected for some titles:

```
>>> from gutenberg.query import get_etexts
INFO:rdflib:RDFLib Version: 4.2.1
>>> from gutenberg.query import get_metadata
>>> print(get_metadata('title', 1)) 
frozenset([u'The Declaration of Independence of the United States of America'])
>>> print(get_metadata('author', 1)) 
frozenset([u'United States President (1801-1809)'])
```

This seems like the relevant parts of the RDF from the dump I downloaded:

```
    <dcterms:creator>
      <pgterms:agent rdf:about="2009/agents/1638">
        <pgterms:webpage rdf:resource="http://en.wikipedia.org/wiki/Thomas_Jefferson"/>
        <pgterms:birthdate rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">1743</pgterms:birthdate>
        <pgterms:name>Jefferson, Thomas</pgterms:name>
        <pgterms:deathdate rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">1826</pgterms:deathdate>
        <pgterms:alias>United States President (1801-1809)</pgterms:alias>
      </pgterms:agent>
    </dcterms:creator>

```

**Comment by MasterOdin** [comment]
I think it'd make more sense to change the [extractor](https://github.com/c-w/Gutenberg/blob/master/gutenberg/query/extractors.py#L50) to prefer `DCTERMS.creator / PGTERMS.name` over `DCTERMS.creator / PGTERMS.alias` which would make getting the author more inline with what you'd see if you went to the [Gutenberg site](https://www.gutenberg.org/ebooks/1).

**Comment by c-w** [comment]
@keithohara: Thanks for reporting this. I finally got some time to work on this project again so this issue is now fixed in the latest master.
