### ISSUE TITLE
pip install gutenberg on debian looks for 

### ISSUE THREAD

**Issue by ArthurX** [c-w/Gutenberg#44]
I have solved it finally.
Once you install libdb5.3-dev
It is OK
but libdb5.1-dev is no longer available
and libdb5.3 is not the same:
It does not create the /usr/include/db.h file

I am now gonna test and use your module.
Thanks a lot in advance!! :)

I do not know whether this is really an issue or my lack of skills.
I tested:
apt-get install libdb5.3
this gives:
libdb5.3 is already the newest version.

This the output of the command line:

> root@RoseWoodSamDebian:/home/arthurx/Python_course/google-python-exercises/basic# pip install gutenberg
Downloading/unpacking gutenberg
  Downloading Gutenberg-0.4.2.tar.gz
  Running setup.py (path:/tmp/pip-build-ZWxwvG/gutenberg/setup.py) egg_info for package gutenberg
    
Downloading/unpacking bsddb3>=6.1.0 (from gutenberg)
  Downloading bsddb3-6.2.1.tar.gz (228kB): 228kB downloaded
  Running setup.py (path:/tmp/pip-build-ZWxwvG/bsddb3/setup.py) egg_info for package bsddb3
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-ZWxwvG/bsddb3/setup.py", line 40, in <module>
        import setup2
      File "setup2.py", line 332, in <module>
        with open(os.path.join(incdir, 'db.h'), 'r') as f :
    IOError: [Errno 2] No such file or directory: '/usr/include/db.h'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-ZWxwvG/bsddb3/setup.py", line 40, in <module>

    import setup2

  File "setup2.py", line 332, in <module>

    with open(os.path.join(incdir, 'db.h'), 'r') as f :

IOError: [Errno 2] No such file or directory: '/usr/include/db.h'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-ZWxwvG/bsddb3
Storing debug log for failure in /root/.pip/pip.log
root@RoseWoodSamDebian:/home/arthurx/Python_course/google-python-exercises/basic#

**Comment by sethwoodworth** [comment]
In debian jessie 8.4 `sudo pip install gutenberg` works if I `sudo apt install libdb5.3-dev` first.  Try finding that package in the syntaptic package manager gui and see if you have a version of the package installed from jessie-backports, testing or unstable.

**Comment by ArthurX** [comment]
Hi Seth,
Thanks!!
It now works!
I have downloaded 100 books.😁😀😂
Arthur
