### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by c-w** [c-w/Gutenberg#47]
I'm no longer regularly working with Project Gutenberg data, so I'm no longer in the position to maintain this project. As such, **I'm looking for a new maintainer**.

What do you get as the maintainer?
- Work on an actively used library.
- Python 2/3 codebase.
- Reasonable test coverage.
- Some low-hanging fruit features to implement and bugs to fix so lots of stuff to do :)

If you are interested in taking over as the maintainer of the Gutenberg project, reply to this issue.

**Comment by sethwoodworth** [comment]
I would love to!  I'm a huge fan of what you've done with the repo, and plan on using it heavily in upcoming months.

**Comment by c-w** [comment]
Thanks for volunteering, @sethwoodworth -- I'm sure the project will be in great hands with you.

I've added you as an owner to this repository.

What's your user-name on PyPI? I'll add you as an owner there too.

**Comment by sethwoodworth** [comment]
Let's go with the `gitenberg` pypi account.

**Comment by sethwoodworth** [comment]
I'm open and willing to work with other contributors as well, and I will keep this issue open in the meantime.  Thank you @c-w for for being a responsible package maintainer, and for creating this excellent project.

**Comment by c-w** [comment]
@sethwoodworth the `gitenberg` account now has owner rights to the [gutenberg package](https://pypi.python.org/pypi/Gutenberg).

**Comment by MasterOdin** [comment]
@c-w @sethwoodworth Do we want to add the ability for Travis to push to PyPI automatically on tags? It's relatively straightforward (https://docs.travis-ci.com/user/deployment/pypi/), just really requiring either of you to do it with an account that has access to PyPI.

**Comment by c-w** [comment]
@MasterOdin: What's your PyPI account? I'll give you permissions to the package.

**Comment by MasterOdin** [comment]
@c-w: I've got two: Master_Odin (main) and Master_Odin_Bot (I use this one inside my travis scripts for pushing to pypi and leave it as a maintainer role).

**Comment by c-w** [comment]
@MasterOdin I added Master_Odin as an owner and Master_Odin_Bot as a maintainer. Go have fun :)

**Comment by c-w** [comment]
@hugovk I see that you've been contributing a lot to this project recently. Thanks a lot for that. I've added you as a commiter so that you can continue doing great work.

**Comment by c-w** [comment]
Closing this since we now have a few more active maintainers.
