### ISSUE TITLE
Remove support for python 3.2

### ISSUE THREAD

**Issue by MasterOdin** [c-w/Gutenberg#49]
The library has some amount of incompatibilities with python 3.2 that it's probably best to just drop it. Current issues being that the requests library doesn't support it (thread on that [here](https://github.com/kennethreitz/requests/issues/3507)). A good deal of other popular packages have already dropped support so it's not unreasonable to do the same here (and there shouldn't really be any modern linux distro that's still using it).

**Comment by sethwoodworth** [comment]
The top few python libraries on PyPI [do not support python 3.2](https://pypi.python.org/pypi/simplejson/3.8.1).  I'm inclined to agree.  Brand new to the organization of this project, so I'm not likely to move quickly.

**Comment by MasterOdin** [comment]
Dropping it also allows for removal of the `from six import u` shim. 

Otherwise, the fix to "support it" would be to peg requests to `requests>=2.5.1,<=2.9.1` (though maybe 2.9.1 or 2.10.0 would work as well).

**Comment by hugovk** [comment]
See PR https://github.com/c-w/Gutenberg/pull/53 to remove support for Python 3.2, and PR https://github.com/c-w/Gutenberg/pull/54 to retain support.

**Comment by ikarth** [comment]
My current humble suggestion: we should drop support for 3.2 for the time being. If support for 3.2 is desired, a fork should be created, to be integrated in the future if someone needs it.

**Comment by sethwoodworth** [comment]
It's been ~2 months.  I see no reason to wait further.  @hugovk I am reviewing #53 now.

**Comment by sethwoodworth** [comment]
> Dropping it also allows for removal of the from six import u shim.

This is very compelling.  Particularly since the `six` docs say that `u()` is only safe in Python2 when used on ASCII data.  The docs also confirm that packages supporting Python3.3+ don't need this shim.
