### ISSUE TITLE
Cannot install on Python 2.7 due to bsddb

### ISSUE THREAD

**Issue by hugovk** [c-w/Gutenberg#52]
- macOS Sierra
- Python 2.7.12
- Gutenberg 0.4.2

``` bash
$ pip install gutenberg
Collecting gutenberg
  Downloading Gutenberg-0.4.2.tar.gz
Collecting bsddb3>=6.1.0 (from gutenberg)
  Using cached bsddb3-6.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Can't find a local Berkeley DB installation.
    (suggestion: try the --berkeley-db=/path/to/bsddb option)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/zm/drwrq_ld04s7vk50p00c9lnw0000gn/T/pip-build-TGvyoe/bsddb3/
```

The [installation instructions in the README](https://github.com/c-w/Gutenberg#installation) say bsddb is only needed for Python 3:

> # Installation
> 
> is project is on PyPI, so I'd recommend that you just install everything from there using your favourite Python package manager.
> 
> ```
> pip install gutenberg
> ```

... 

> # Python 3
> 
> This package depends on BSD-DB. The bsddb module was removed from the Python standard library since version 2.7. This means that if you wish to use gutenberg on Python 3, you will need to manually install BSD-DB.

Is that not the case? Is bsddb3 needed for Python 2?

**Comment by MasterOdin** [comment]
No, you shouldn't need to install bsddb3 and I guess there might be a bug on when setup.py tries to figure out what requirements to install for you.

However, you do need to install Berkeley DB separately from Gutenberg as python just comes with the module to connect to it and not the actual DB (which should be clarified in the instructions).

On Mac though, use [homebrew](https://homebrew.sh) to install it via `brew install berkeley-db4`, and then try again to do `pip install gutenberg`

**Comment by hugovk** [comment]
It'd be great to put this stuff in a Dependencies section for the README before Installation, with the instructions for each OS.

**Comment by c-w** [comment]
Thanks, @MasterOdin, for the macOS instructions. I created #69 to include the instructions in our readme.
