### ISSUE TITLE
Downloaded texts contain unicode replacement characters instead of accents

### ISSUE THREAD

**Issue by moredatarequired** [c-w/Gutenberg#62]
When I download a book, e.g., 

`python3 -m gutenberg.acquire.text 2000 2000.txt`

All the accented characters are replaced with u'\ufffd'. When I download the same file from Gutenberg directly (https://www.gutenberg.org/ebooks/2000.txt.utf-8), it is UTF-8 and all characters are intact.

**Comment by c-w** [comment]
@moredatarequired: This bug was fixed in #65. Thanks for the bug report!
Please update to the latest version of the code and let us know if you're still experiencing the issue.

**Comment by c-w** [comment]
@moredatarequired Closing this for now as the issue seems fixed -- if you still experience this problem, please feel free to re-open.
