### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by MasterOdin** [c-w/Gutenberg#83]
@c-w Do we want to release a new version now with the previous two PRs? Since we're moving to a new version of a dependency and adding a new flag, I'd say it should be 0.5.0 release, but I leave the final decision to you. I'm assuming that all new releases will go through you?

Note: You should be able to just draft a release through github, and then once it successfully builds on Travis, it'll be auto published to pypi, so it's nice and easy to do all through CI tools.

**Comment by c-w** [comment]
I agree that a new minor release instead of a point release is the right thing to do.
Let's see if it all works end-to-end via Travis :)

**Comment by c-w** [comment]
Great, everything worked and we now have [v0.5.0](https://pypi.python.org/pypi?:action=display&name=Gutenberg&version=0.5.0) published to PyPI.
